---
name: github-trending-website
description: Local codebase analysis for github-trending-website
doc_version:
---

# github-trending-website Codebase

## Description

Local codebase analysis and documentation generated from code analysis.

**Path:** `D:\github\2015\08\github-trending-website`
**Files Analyzed:** 42
**Languages:** TypeScript
**Analysis Depth:** deep

## When to Use This Skill

Use this skill when you need to:
- Understand the codebase architecture and design patterns
- Find implementation examples and usage patterns
- Review API documentation extracted from code
- Check configuration patterns and best practices
- Explore test examples and real-world usage
- Navigate the codebase structure efficiently

## ⚡ Quick Reference

### Codebase Statistics

**Languages:**
- **TypeScript**: 42 files (100.0%)

**Analysis Performed:**
- ✅ API Reference (C2.5)
- ✅ Dependency Graph (C2.6)
- ✅ Design Patterns (C3.1)
- ✅ Test Examples (C3.2)
- ✅ Configuration Patterns (C3.4)
- ✅ Architectural Analysis (C3.7)
- ✅ Project Documentation (C3.9)

## 🏗️ Architecture Overview

*From C3.7 architectural analysis*

**Detected Architectural Patterns:**

- **Layered Architecture (2-tier)** (confidence: 0.85)

*Total: 1 architectural patterns detected*

*See `references/architecture/` for complete architectural analysis*

## ⚙️ Configuration Patterns

*From C3.4 configuration analysis*

**Configuration Files Analyzed:** 27
**Total Settings:** 10071
**Patterns Detected:** 0

**Configuration Types:**
- unknown: 27 files

*See `references/config_patterns/` for detailed configuration analysis*

## 📖 Project Documentation

*Extracted from markdown files in the project (C3.9)*

**Total Documentation Files:** 30
**Categories:** 3

### Overview

- **API 状态说明**: **API 状态说明**
- **CLAUDE.md**: **CLAUDE.md**
- **README**: Sections: Getting Started, Learn More, Deploy on Vercel
- **🎉 功能恢复完成报告**: **🎉 功能恢复完成报告**
- **GitHub Trending 搜索功能操作指南**: **GitHub Trending 搜索功能操作指南**
- *...and 1 more*

### Api

- **API Reference: cloudflare-env.d.ts**: **API Reference: cloudflare-env.d.ts**
- **API Reference: DatePicker.tsx**: **API Reference: DatePicker.tsx**
- **API Reference: global-error.tsx**: **API Reference: global-error.tsx**
- **API Reference: home-client.tsx**: **API Reference: home-client.tsx**
- **API Reference: import-data.ts**: **API Reference: import-data.ts**
- *...and 17 more*

### Other

- **Configuration Extraction Report**: **Configuration Extraction Report**
- **GitHub Trending 数据库数据缺失分析报告**: **GitHub Trending 数据库数据缺失分析报告**

*See `references/documentation/` for all project documentation*

## 📚 Available References

This skill includes detailed reference documentation:

- **API Reference**: `references/api_reference/` - Complete API documentation
- **Dependencies**: `references/dependencies/` - Dependency graph and analysis
- **Patterns**: `references/patterns/` - Detected design patterns
- **Configuration**: `references/config_patterns/` - Configuration patterns
- **Architecture**: `references/architecture/` - Architectural patterns
- **Documentation**: `references/documentation/` - Project documentation

---

**Generated by Skill Seeker** | Codebase Analyzer with C3.x Analysis
